#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ─────────────────────────────────────────────────────────────────
# Glanceboard — One-Line Pi Installer
#
# Run this on your Raspberry Pi after first boot:
#   curl -sSL https://raw.githubusercontent.com/google-gemini/glanceboard/main/pi/install.sh | bash
#
# This script will:
#   1. Download the Glanceboard Pi files from GitHub
#   2. Install all system dependencies
#   3. Ask for your Display URL
#   4. Set up the systemd service
#   5. Test the connection
# ─────────────────────────────────────────────────────────────────

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
echo -e "${BLUE}${BOLD}  🖼️  Glanceboard — E-Ink Display Installer${NC}"
echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
echo ""

# ── Step 1: Download files ──────────────────────────────────────
echo -e "${BOLD}📥 Step 1: Downloading Glanceboard files...${NC}"

INSTALL_DIR="$HOME/glanceboard"
mkdir -p "$INSTALL_DIR"

# Download the Pi files from GitHub
FILES=(
    "pi/display_update.py"
    "pi/setup_pi.sh"
    "pi/eink-display.service"
)

REPO_URL="https://raw.githubusercontent.com/google-gemini/glanceboard/main"

for file in "${FILES[@]}"; do
    filename=$(basename "$file")
    echo "   Downloading $filename..."
    curl -sSL "$REPO_URL/$file" -o "$INSTALL_DIR/$filename"
done

echo -e "${GREEN}   ✓ Files downloaded${NC}"

# ── Step 2: Run setup script ────────────────────────────────────
echo ""
echo -e "${BOLD}🔧 Step 2: Installing dependencies...${NC}"
echo "   (This may take a few minutes)"
echo ""

cd "$INSTALL_DIR"
chmod +x setup_pi.sh
bash setup_pi.sh

# ── Step 3: Configure Display URL ───────────────────────────────
echo ""
echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
echo -e "${BOLD}🔗 Step 3: Connect to Glanceboard${NC}"
echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
echo ""
echo "Now you need your Pi Display Image URL."
echo ""
echo -e "${YELLOW}To find it:${NC}"
echo "  1. Go to your Glanceboard dashboard (in your browser)"
echo "  2. Click Settings → E-Ink Display Setup"
echo "  3. Click 📋 Copy URL"
echo "  4. Paste it here"
echo ""

CONFIG_FILE="$HOME/.glanceboard.conf"

# Check if already configured
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
    if [ -n "$EINK_SERVER_URL" ]; then
        echo -e "${GREEN}Found existing configuration!${NC}"
        echo "  Current URL: ${EINK_SERVER_URL:0:60}..."
        echo ""
        read -p "Keep this URL? (y/n): " keep_url
        if [ "$keep_url" = "y" ] || [ "$keep_url" = "Y" ]; then
            echo -e "${GREEN}   ✓ Keeping existing URL${NC}"
        else
            EINK_SERVER_URL=""
        fi
    fi
fi

if [ -z "$EINK_SERVER_URL" ]; then
    while true; do
        echo -e "${BOLD}Paste your Display URL:${NC}"
        read -r display_url

        if [ -z "$display_url" ]; then
            echo -e "${RED}   ✗ URL cannot be empty. Try again.${NC}"
            continue
        fi

        # Basic URL validation
        if [[ "$display_url" == http* ]]; then
            EINK_SERVER_URL="$display_url"
            break
        else
            echo -e "${RED}   ✗ That doesn't look like a URL. It should start with https://...${NC}"
        fi
    done
fi

# Save configuration
cat > "$CONFIG_FILE" << EOF
# Glanceboard Configuration
# Generated by install.sh on $(date)

# Your Pi Display Image URL (from the Glanceboard dashboard)
EINK_SERVER_URL="$EINK_SERVER_URL"

# How often to check for new images (in seconds, default: 300 = 5 min)
EINK_POLL_INTERVAL=300

# Where to store the last image hash (for change detection)
EINK_HASH_FILE=/tmp/eink_last_hash.txt
EOF

echo -e "${GREEN}   ✓ Configuration saved to $CONFIG_FILE${NC}"

# ── Step 4: Install systemd service ─────────────────────────────
echo ""
echo -e "${BOLD}📦 Step 4: Setting up auto-start service...${NC}"

# Get current username (not hardcoded to 'pi')
CURRENT_USER=$(whoami)

# Create the systemd service with the configured URL
cat > "/tmp/eink-display.service" << EOF
[Unit]
Description=Glanceboard E-Ink Display Updater
Documentation=https://github.com/google-gemini/glanceboard
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=$CURRENT_USER
WorkingDirectory=/home/$CURRENT_USER/glanceboard
EnvironmentFile=/home/$CURRENT_USER/.glanceboard.conf
ExecStart=/usr/bin/python3 /home/$CURRENT_USER/glanceboard/display_update.py --once

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=glanceboard

# Security
NoNewPrivileges=false
ProtectSystem=false

[Install]
WantedBy=multi-user.target
EOF

# Also create a timer to run it periodically
cat > "/tmp/eink-display.timer" << EOF
[Unit]
Description=Glanceboard Display Update Timer

[Timer]
OnBootSec=2min
OnUnitActiveSec=15min
AccuracySec=1min

[Install]
WantedBy=timers.target
EOF

sudo cp /tmp/eink-display.service /etc/systemd/system/
sudo cp /tmp/eink-display.timer /etc/systemd/system/
sudo systemctl daemon-reload

echo -e "${GREEN}   ✓ Service installed${NC}"

# ── Step 5: Test connection ─────────────────────────────────────
echo ""
echo -e "${BOLD}🧪 Step 5: Testing connection...${NC}"

# Try to reach the URL
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$EINK_SERVER_URL" 2>/dev/null || echo "000")

if [ "$HTTP_STATUS" = "200" ]; then
    echo -e "${GREEN}   ✓ Successfully connected! Image URL is reachable.${NC}"
elif [ "$HTTP_STATUS" = "000" ]; then
    echo -e "${YELLOW}   ⚠ Could not reach the URL. This might be because:${NC}"
    echo "     - No image has been generated yet (generate one in the dashboard first)"
    echo "     - The URL might be incorrect"
    echo "     Don't worry — the service will keep trying!"
else
    echo -e "${YELLOW}   ⚠ Got HTTP status $HTTP_STATUS. This might fix itself after you generate your first image.${NC}"
fi

# ── Step 6: Enable and start ────────────────────────────────────
echo ""
echo -e "${BOLD}🚀 Step 6: Starting the service...${NC}"

sudo systemctl enable eink-display.timer
sudo systemctl start eink-display.timer

echo -e "${GREEN}   ✓ Glanceboard service is running!${NC}"

# ── SPI Check ───────────────────────────────────────────────────
SPI_NEEDS_REBOOT=false
if ! grep -q "^dtparam=spi=on" /boot/firmware/config.txt 2>/dev/null && \
   ! grep -q "^dtparam=spi=on" /boot/config.txt 2>/dev/null; then
    SPI_NEEDS_REBOOT=true
fi

# ── Done ────────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ✅ Glanceboard is installed and running!${NC}"
echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
echo ""

if [ "$SPI_NEEDS_REBOOT" = true ]; then
    echo -e "${YELLOW}${BOLD}⚠️  IMPORTANT: SPI was just enabled. You need to reboot:${NC}"
    echo -e "   ${BOLD}sudo reboot${NC}"
    echo ""
fi

echo "Your display will update every 15 minutes."
echo ""
echo "Useful commands:"
echo "  Check status:     sudo systemctl status eink-display.timer"
echo "  View logs:        journalctl -u eink-display -f"
echo "  Update now:       sudo systemctl start eink-display"
echo "  Change URL:       nano ~/.glanceboard.conf"
echo "  Reinstall:        curl -sSL https://raw.githubusercontent.com/google-gemini/glanceboard/main/pi/install.sh | bash"
echo ""
echo -e "Now go to your Glanceboard dashboard and click ${BOLD}\"🎨 Generate Now\"${NC} to create your first image!"
echo ""
